-- Sinonimi di ricerca: varianti dialettali e lessicali salentine.
-- term: normalizzato (minuscole, senza accenti). Espansi da expand_query_terms().
INSERT INTO search_synonyms (term, synonyms) VALUES
  ('purpu','{"polpo","polipi"}'),
  ('polpo','{"purpu"}'),
  ('te lu purpu','{"polpo"}'),
  ('pizzica','{"taranta","musica popolare","pizzica pizzica"}'),
  ('taranta','{"pizzica","notte della taranta"}'),
  ('festa patronale','{"festa del santo","festeggiamenti patronali","patrono"}'),
  ('festa del santo','{"festa patronale","festeggiamenti patronali"}'),
  ('mercatino','{"fiera","mercato"}'),
  ('mercatini','{"fiere","mercatino"}'),
  ('fiera','{"mercatino","mercato"}'),
  ('sagre','{"sagra"}'),
  ('sagra','{"festa gastronomica","sagre"}'),
  ('luminarie','{"luminaria","illuminazioni","luci artistiche"}'),
  ('processione','{"funzioni religiose","processioni"}'),
  ('frisa','{"frise","frisella","friselle"}'),
  ('pasticciotto','{"pasticciotti"}'),
  ('pittule','{"pettole","pettule"}'),
  ('pettole','{"pittule"}'),
  ('concerto','{"live","concerti","esibizione"}'),
  ('dj','{"dj set","djset","consolle"}'),
  ('fuochi','{"fuochi d''artificio","fuochi artificiali","pirotecnici","spettacolo pirotecnico"}'),
  ('pirotecnici','{"fuochi d''artificio"}'),
  ('banda','{"concerto bandistico","bande musicali"}'),
  ('scapece','{"scapece gallipolina"}'),
  ('turciddhrule','{"mustaccioli"}'),
  ('trampoli','{"trampolieri"}'),
  ('fiocchi di neve','{"neve artificiale"}'),
  ('spettacolo','{"show","rappresentazione"}'),
  ('degustazione','{"assaggio","degustazioni"}'),
  ('vino','{"enogastronomia","calici","cantina"}')
ON CONFLICT (term) DO UPDATE SET synonyms = EXCLUDED.synonyms;
