import { getEventBySlug } from './_shared/event-repository.mjs';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function cleanUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
function romeOffset(date){try{const part=new Intl.DateTimeFormat('en',{timeZone:'Europe/Rome',timeZoneName:'longOffset'}).formatToParts(new Date(`${date}T12:00:00Z`)).find(p=>p.type==='timeZoneName')?.value||'GMT+01:00';return part.replace('GMT','');}catch{return '+01:00';}}
export default async(req,context)=>{
 const slug=context.params?.slug||new URL(req.url).pathname.split('/').filter(Boolean).pop();
 const event=await getEventBySlug(slug);
 if(!event)return new Response('<!doctype html><html lang="it"><meta charset="utf-8"><title>Evento non trovato</title><body><h1>Evento non trovato</h1><p><a href="/eventi.html">Torna agli eventi</a></p></body></html>',{status:404,headers:{'content-type':'text/html; charset=utf-8'}});
 const base=new URL(req.url).origin,canonical=`${base}/eventi/${encodeURIComponent(event.slug)}`;
 const start=`${event.startDate}${event.startTime?`T${event.startTime}:00${romeOffset(event.startDate)}`:''}`;
 const end=`${event.endDate}${event.endTime?`T${event.endTime}:00${romeOffset(event.endDate)}`:''}`;
 const statusMap={cancelled:'https://schema.org/EventCancelled',postponed:'https://schema.org/EventPostponed'};
 const ld={ '@context':'https://schema.org','@type':'Event',name:event.title,description:event.description,startDate:start,endDate:end,eventStatus:statusMap[event.status]||'https://schema.org/EventScheduled',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',location:{'@type':'Place',name:event.venue||event.town,address:{'@type':'PostalAddress',streetAddress:event.address||'',addressLocality:event.town,addressRegion:'LE',addressCountry:'IT'},geo:event.latitude!=null&&event.longitude!=null?{'@type':'GeoCoordinates',latitude:event.latitude,longitude:event.longitude}:undefined},url:canonical,image:event.imageUrl?[event.imageUrl]:undefined,organizer:event.organizer?{'@type':'Organization',name:event.organizer}:undefined,isAccessibleForFree:event.priceType==='free',offers:event.priceType==='free'?{'@type':'Offer',price:'0',priceCurrency:'EUR',url:cleanUrl(event.bookingUrl||event.sourceUrl)}:undefined};
 const sources=(event.sources||[]).map(s=>`<li><a href="${esc(cleanUrl(s.url))}" target="_blank" rel="nofollow noopener">${esc(s.name||'Fonte')}</a></li>`).join('');
 const html=`<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(event.title)} | Benvenuti in Salento</title><meta name="description" content="${esc((event.description||`${event.title} a ${event.town}`).slice(0,155))}"><link rel="canonical" href="${esc(canonical)}"><link rel="stylesheet" href="/styles/main.css"><link rel="stylesheet" href="/styles/events.css"><script type="application/ld+json">${JSON.stringify(ld).replace(/</g,'\\u003c')}</script></head><body><header class="event-mini-header"><a href="/"><img src="/assets/images/benvenuti-in-salento-logo.png" alt="" width="44">Benvenuti in Salento</a><a href="/eventi.html">Tutti gli eventi</a></header><main class="event-detail-shell"><article class="event-detail-card">${event.imageUrl?`<img class="event-detail-image" src="${esc(cleanUrl(event.imageUrl))}" alt="">`:''}<p class="event-kicker">${esc(event.primaryCategory)}</p><h1>${esc(event.title)}</h1>${event.status==='cancelled'?'<p class="event-alert">Evento annullato</p>':event.status==='postponed'?'<p class="event-alert">Evento rinviato: verifica la fonte</p>':''}<p class="event-lead">${esc(event.description||'Consulta la fonte ufficiale per il programma completo.')}</p><dl class="event-facts"><div><dt>Quando</dt><dd>${esc(event.startDate)}${event.endDate!==event.startDate?` – ${esc(event.endDate)}`:''} ${esc(event.originalTimeText||event.startTime||'')}</dd></div><div><dt>Dove</dt><dd>${esc([event.venue,event.locality,event.town].filter(Boolean).join(' · '))}</dd></div><div><dt>Ingresso</dt><dd>${esc(event.priceType==='free'?'Gratuito':event.priceText||'Da verificare')}</dd></div><div><dt>Verifica</dt><dd>${esc(event.verificationLevel)}</dd></div></dl><h2>Fonti</h2><ul>${sources||`<li><a href="${esc(cleanUrl(event.sourceUrl))}" rel="nofollow noopener">${esc(event.sourceName)}</a></li>`}</ul><p class="event-source-note">Controlla sempre la fonte prima di partire: programmi e orari possono cambiare.</p></article></main></body></html>`;
 return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=300,stale-while-revalidate=3600','x-content-type-options':'nosniff'}});
};
export const config={path:'/eventi/:slug'};
